import Image from "next/image"

const Execute = () => {
    return (
        <div id="executes">
            <div>
                <div 
                    className="
                        w-[349px]
                        lg:w-[884px]
                        lg:text-3xl
                        xl:text-5xl
                        text-[24px]
                        font-bold
                        text-[var(--hero)]
                        flex 
                        justify-center
                        mx-auto
                        text-center
                        mb-[20px]
                        lg:mb-[40px]
                        mt-[100px]
                    "
                >
                    Everything You Need to Plan & Execute 
                    Flawless Events
                </div>
                <p
                    className="
                        text-[var(--register-event)]
                        text-[14px]
                        lg:text-[14px]
                        xl:text-[16px]
                        w-[338px]
                        lg:w-[750px]
                        leading-normal
                        mb-[50px]
                        lg:mb-[70px]
                        mx-auto
                        text-center
                    "
                >
                    Whether you&apos;re an event planner, organization, or individual, Setup Suite gives you the power to create seamless, well-organized experiences.
                </p>
            </div>
            <div 
                className="
                    flex
                    flex-col
                    lg:flex-row
                    justify-center
                    items-center
                    lg:justify-center
                    xl:justify-center
                    lg:gap-[20px]
                "
            >
            <div 
                className="
                    shadow-2xl
                    bg-[var(--white)]
                    w-[315px]
                    py-8
                    lg:mb-12
                    mb-3
                "
            >
                <div>
                    <h1 
                        className="
                            lg:text-[20px]
                            text-[18px]
                            font-black
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            mb-[10px]
                            mx-auto
                        "
                    >
                        <Image 
                            src="/images/eventreg.svg"
                            alt="event reg"
                            width={41}
                            height={41}
                            className="mb-[20px]"
                        />
                        Smart Event Registration & Check-in
                    </h1>
                    <p 
                        className="
                            lg:text-[16px]
                            text-[14px]
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            leading-normal
                            mx-auto
                        "
                    >
                        Eliminate manual entry with digital QR codes and real-time attendee tracking.
                    </p>
                </div>
            </div>
            <div 
                className="
                    shadow-2xl
                    bg-[var(--white)]
                    w-[315px]
                    py-8
                    lg:mb-12
                    mb-3
                "
            >
                <div>
                    <h1 
                        className="
                            lg:text-[20px]
                            text-[18px]
                            font-black
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            mb-[10px]
                            mx-auto
                        "
                    >
                        <Image 
                            src="/images/eventanalytic.svg"
                            alt="event reg"
                            width={41}
                            height={41}
                            className="mb-[20px]"
                        />
                        Comprehensive Event Analytics
                    </h1>
                    <p 
                        className="
                            lg:text-[16px]
                            text-[14px]
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            leading-normal
                            mx-auto
                        "
                    >
                        Gain insights into attendance, engagement, and logistics with powerful reports.
                    </p>
                </div>
            </div>
            <div 
                className="
                    shadow-2xl
                    bg-[var(--white)]
                    w-[315px]
                    py-8
                    lg:mb-12
                    mb-3
                "
            >
                <div>
                    <h1 
                        className="
                            lg:text-[20px]
                            text-[18px]
                            font-black
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            mb-[10px]
                            mx-auto
                        "
                    >
                        <Image 
                            src="/images/souvenirmanage.svg"
                            alt="event reg"
                            width={41}
                            height={41}
                            className="mb-[20px]"
                        />
                        Vendor & Souvenir Management.
                    </h1>
                    <p 
                        className="
                            lg:text-[16px]
                            text-[14px]
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            leading-normal
                            mx-auto
                        "
                    >
                        Easily coordinate with vendors and streamline distribution of event materials.
                    </p>
                </div>
            </div>
            </div>
            <div 
                className="
                    flex
                    flex-col
                    lg:flex-row
                    justify-center
                    items-center
                    lg:justify-center
                    xl:justify-center
                    lg:gap-[20px]
                "
            >
            <div 
                className="
                    shadow-2xl
                    bg-[var(--white)]
                    w-[315px]
                    py-8
                    lg:mb-12
                    mb-3
                "
            >
                <div>
                    <h1 
                        className="
                            lg:text-[20px]
                            text-[18px]
                            font-black
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            mb-[10px]
                            mx-auto
                        "
                    >
                        <Image 
                            src="/images/plusone.svg"
                            alt="event reg"
                            width={41}
                            height={41}
                            className="mb-[20px]"
                        />
                        Plus-One & Guest List Management
                    </h1>
                    <p 
                        className="
                            lg:text-[16px]
                            text-[14px]
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            leading-normal
                            mx-auto
                        "
                    >
                        Track RSVPs, manage guest allowances, and ensure a personalized experience.

                    </p>
                </div>
            </div>
            <div 
                className="
                    shadow-2xl
                    bg-[var(--white)]
                    w-[315px]
                    py-8
                    lg:mb-12
                    mb-3
                "
            >
                <div>
                    <h1 
                        className="
                            lg:text-[20px]
                            text-[18px]
                            font-black
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            mb-[10px]
                            mx-auto
                        "
                    >
                        <Image 
                            src="/images/accreditation.svg"
                            alt="event reg"
                            width={41}
                            height={41}
                            className="mb-[20px]"
                        />
                        Onsite Accreditation & Printables
                    </h1>
                    <p 
                        className="
                            lg:text-[16px]
                            text-[14px]
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            leading-normal
                            mx-auto
                        "
                    >
                        Make event access smooth with onsite badge printing and verification.

                    </p>
                </div>
            </div>
            <div 
                className="
                    shadow-2xl
                    bg-[var(--white)]
                    w-[315px]
                    py-8
                    lg:mb-12
                    mb-3
                "
            >
                <div>
                    <h1 
                        className="
                            lg:text-[20px]
                            text-[18px]
                            font-black
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            mb-[10px]
                            mx-auto
                        "
                    >
                        <Image 
                            src="/images/pricing.svg"
                            alt="event reg"
                            width={41}
                            height={41}
                            className="mb-[20px]"
                        />
                        Flexible Pricing & 
                        Access
                    </h1>
                    <p 
                        className="
                            lg:text-[16px]
                            text-[14px]
                            text-[var(--register-event)]
                            lg:w-[269px]
                            w-[230px]
                            leading-normal
                            mx-auto
                        "
                    >
                        Choose from subscription plans or pay-per-event options that suit your needs.
                    </p>
                </div>
            </div>
            </div>
        </div>
    )
}

export default Execute